/**
 * Created by Administrator on 2016/6/6.
 */
angular.module('kaifanla',['ng','ngRoute','ngAnimate'])
    .controller('parentCtrl',function($scope,$location){
        $scope.jump=function(url){
            $location.path(url);
        }
    })
    .controller('startCtrl',function($scope){
    })
    .controller('mainCtrl',function($scope,$http){
        $scope.hasMoreData=true;//服务器是否还有更多数据可以加载
        //从服务器端获取最开始的5条菜品数据，声明为Model数据，绑定到View
        $scope.dishList=[];
        $http.get('data/dish_getbypage.php?start=0').success(function(data){
            $scope.dishList=data;//把服务器返回的异步数据声明为Model数据
        });
        $scope.loadMore=function(){
            $http.get('data/dish_getbypage.php?start='+$scope.dishList.length).success(function(data){
                if(data.length<5){
                    $scope.hasMoreData=false;
                }
                $scope.dishList=$scope.dishList.concat(data);
            });
        };
        //监视Model数据kw的改变，只要改变就发起服务请求
        $scope.$watch('kw',function(){
            if(!$scope.kw){//模型数据改变为空
                return;
            }else{
                $http.get('data/dish_getbykw.php?kw='+$scope.kw).success(function(data){
                    $scope.dishList=data;
                });
            }
        })
    })
    .controller('detailCtrl',function($scope,$routeParams,$http){
        $http.get('data/dish_getbyid.php?did='+$routeParams.dno).success(function(data){
            $scope.dishDetail=data[0];
        });
    })
    .controller('orderCtrl',function($scope,$http,$routeParams){
        $scope.isConfirm=true;
        $scope.pay=function(){
            $scope.isConfirm=false;
            $http.get('data/order_add.php?user_name='+$scope.user_name+'&sex='+$scope.sex+'&phone='+$scope.phone+'&addr='+$scope.addr+'&did='+$routeParams.rno)
                .success(function(data){
                    $scope.menu=data;
                });
        }
    })
    .controller('myOrderCtrl',function($scope,$http){
        $http.get('data/order_getbyphone.php?phone=15776620639').success(function(data){
            //电话号码目前是定值，可以通过用户登录信息获取电话号码进行查看订单
            $scope.orderDetail=data;
        });
    })
    .controller('moreCtrl',function(){

    })
    .config(function($routeProvider){
        $routeProvider
            .when('/start',{
                templateUrl:'template/start.html',
                controller:'startCtrl'
            })
            .when('/main',{
                templateUrl:'template/main.html',
                controller:'mainCtrl'
            })
            .when('/detail/:dno',{
                templateUrl:'template/detail.html',
                controller:'detailCtrl'
            })
            .when('/order/:rno',{
                templateUrl:'template/order.html',
                controller:'orderCtrl'
            })
            .when('/myOrder',{
                templateUrl:'template/myOrder.html',
                controller:'myOrderCtrl'
            })
            .when('/more',{
                templateUrl:'template/more.html',
                controller:'moreCtrl'
            })
            .otherwise({
                redirectTo:'/start',
            })
    })